version: 2.1

jobs:
  say_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Printing_Hello
          command: echo "Hello"
  
  say_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Printing_World 
          command: echo "World!"

workflows:
  say_hello_world:
    jobs:
      - say_hello
      - say_world