version: 2.1

jobs:
  say_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Printing_Hello
          command: echo "Hello"
  
  say_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Printing_World 
          command: echo "World!"

  printing_env_var:
    docker:
    - image: circleci/node:13.8.0
    steps:
      - run: 
          command: echo $My_Name

workflows:
  say_hello_world:
    jobs:
      - say_hello
      - say_world:
          requires: 
            - say_hello
      - printing_env_var